import type { Metadata } from 'next'
import '@/app/globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
// import '@fontsource/roboto/300.css';
// import '@fontsource/roboto/400.css';
// import '@fontsource/roboto/500.css';
// import '@fontsource/roboto/700.css';
import Container from '@mui/material/Container';
import CustomThemeProvider from '@/shared/components/CustomThemeProvider';

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Container className='container-xxl p-4'>
          <CustomThemeProvider>
            {children}
          </CustomThemeProvider>
        </Container>
      </body>
    </html>
  )
}
